print ("please enter the following informacion:")
first= input('first name:')
lastName=input ('Last Name:')
Email=input('Email Address:')
job=input('Job title:')
id=input('id Number:')
phone=input('Phone Number:')
print("complete aditional information")
age=int(input ('what is your age?'))
sex= input ('your sex is?')

print('\n---------------------')
print('\nYour card ID is,')
print (f"{lastName.upper()}, {first.capitalize()}, ") 
print (Email.lower())
print(job.title()) 
print (f"ID: {id}")
print(phone)
output= f'Your additional information is: age {age} sex {sex}'
print(output)
print('\n---------------------')